"""Small, source-agnostic deterministic analytics core.

The public API deliberately consists of typed contracts and a handful of
deterministic operations.  Optional readers (Excel and Parquet) are imported
only when used, so the package remains installable in a clean offline Python
environment.
"""

from .contracts import (
    AggregationSpec,
    CanonicalMapping,
    CapabilityDescriptor,
    DataAssetRef,
    DocumentRef,
    FieldRef,
    IncidentRecord,
    IdentityCandidate,
    IdentityDecision,
    IdentityEvidence,
    ImplementationTransition,
    KnowledgeDelta,
    LEMRef,
    OntologyItem,
    OperationReceipt,
    OperationResultRef,
    OperationSpec,
    PhaseTimingRecord,
    PreparedAssetDescriptor,
    PreparedAssetRef,
    RequirementAnalysisPlan,
    RequirementAnalysisTask,
    RequirementRecord,
    RunTelemetrySummary,
    TableRef,
    TelemetryEvent,
)
from .workspace import (
    AllowedRootError,
    DEFAULT_CORE_VERSION,
    DEFAULT_SKILL_VERSION,
    RunContext,
    require_allowed_roots,
)
from .sources import discover, preview, register_source, read_rows
from .profiling import profile_rows, profile_source
from .normalization import normalize_rows, normalize_value, observation_as_of, parse_date, parse_number
from .identity import apply_decision, generate_candidates, mapping_coverage
from .mapping_view import IdentityMappingView, MappingCompletenessAdvisory
from .semantic_advisory import SemanticPromotionSuggestion, suggest_semantic_promotions
from .relationships import measure_relationship
from .populations import PopulationLedger
from .aggregation import aggregate_rows
from .artifacts import write_artifact, write_manifest
from .reproduction import compare_results, reproduce
from .cache import RunCache
from .telemetry import TelemetryRecorder
from .enterprise_model import LivingEnterpriseModel
from .lem_projection import LEMCommittedBinding, LEMProjection, LivingEnterpriseModelProjector
from .entity_resolution import (
    EntityResolutionResult,
    IdentityDomainScope,
    IdentityDomainRequest,
    EntityResolutionWorkspace,
    IdentityDomainReservation,
    ResolutionCapacity,
    ResolutionCommit,
    StaleIdentityScopeError,
    WorkerLease,
    replay_ready_commits,
)
from .catalog import capability_catalog, get_capability
from .runtime import CoreExecutionResult, CoreRuntime
from .autopilot import ActionDispatcher, AutopilotTick, LocalRunAutopilot
from .coordinator import (
    CONTROL_PLANE_DIRNAME,
    COORDINATOR_EVENTS_FILENAME,
    COORDINATOR_LOCK_FILENAME,
    COORDINATOR_SPEC_FILENAME,
    COORDINATOR_STATE_FILENAME,
    PRODUCT_REGENERATION_ORIGIN,
    CommandRoleAdapter,
    CodexExecConfig,
    CoordinatorConflictError,
    CoordinatorError,
    CoordinatorIntegrityError,
    CoordinatorProductionBindingMismatch,
    CoordinatorPublicationError,
    CoordinatorRunSpec,
    CoordinatorStatus,
    CodexRoleAdapter,
    MappingRoleAdapter,
    PlannerActionProvider,
    RequirementPlannerProvider,
    RoleAdapter,
    RoleExecution,
    RoleRunner,
    RunCoordinator,
    ROLE_MODEL_CONTRACT,
    ROLE_ACTION_CONTRACT,
    ACTION_ROLE_CONTRACT,
    PRODUCTION_ROLE_MODEL_CONTRACT,
    PRODUCTION_ROLE_ACTION_CONTRACT,
    build_role_prompt,
    logical_action_fingerprint,
    production_role_routing,
    role_model_route,
    role_route_for_action,
    start_coordinator,
    validate_role_action_contract,
)
from .supervisor import (
    SUPERVISOR_ATTENTION_STATUSES,
    SUPERVISOR_CLEAN_STATUSES,
    SUPERVISOR_ROLE,
    CodexSupervisorAdapter,
    FoundrySupervisor,
    SupervisorAgent,
    SupervisorObservation,
    SupervisorRepairResult,
    SupervisorResult,
    build_supervisor_prompt,
)
from .workbench import (
    CatalogCounts,
    DataRoom,
    DataRoomCatalogEntry,
    DataRoomMember,
    DataRoomWorkbench,
    PreparedAsset,
)
from .prepared import PreparedAssetRegistry
from .product_review import (
    ProductCandidate,
    ProductReview,
    ProductRevision,
    ProductRevisionPointer,
    ProductReviewStore,
    PublishAuthorization,
    activate_product_revision,
    authorize_product_publish,
    begin_product_revision,
    canonical_hash as product_canonical_hash,
    discard_stale_product_candidate,
    record_product_candidate,
    record_product_review,
)
from .semantic_store import (
    ContextPayloadRef,
    SemanticSelectionRef,
    SemanticSnapshotRef,
    SemanticSnapshotStore,
    canonical_context_payload,
)
from .analysis import (
    ANALYSIS_SOURCE_MAP_ENV,
    BoundAnalysisContext,
    CatalogSnapshot,
    ControlledScriptRunner,
    ScriptExecutionReceipt,
    ScriptRunReport,
    ScriptValidationResult,
    load_bound_analysis_context,
    load_selected_source_ids,
)
from .analytical_artifacts import (
    ANALYTICAL_ARTIFACT_SCHEMA_VERSION,
    ANALYTICAL_ARTIFACT_TYPES,
    AnalyticalArtifact,
    AnalyticalArtifactError,
    AnalyticalArtifactValidationError,
    DataProfileArtifact,
    KpiTableArtifact,
    SegmentProfilesArtifact,
    SegmentationModelArtifact,
    artifact_from_dict,
    canonical_content_hash,
    canonical_json,
)
from .analytics_toolkit import (
    AnalyticsDependencyError,
    AnalyticsInputError,
    MetricDefinition,
    TabularInput,
    compute_kpi_table,
    fingerprint_source,
    ingest_tabular,
    load_tabular,
    profile_data,
    score_segments,
    segment_customers,
)
from .analyst_workspace import (
    AnalystAnswer,
    AnalystBrief,
    AnalystSource,
    AnalystWorkspace,
    AnalyticalRelationshipEvidence,
    BusinessReviewAdapter,
    DataInsufficiencyConclusion,
    EvidenceNote,
    IdentityDomainProposal,
    ReviewFinding,
    SpecialistMemo,
    SpecialistTask,
)
from .requirement_planning import (
    PLANNER_INCIDENT_FILENAME,
    SUPERVISOR_PLAN_FILENAME,
    PlannerAction,
    RequirementExecutionGroup,
    RequirementExecutionPlan,
    RequirementRunSnapshot,
    RequirementSupervisorWorkspace,
    compact_catalog_payload,
)
from .integration import (
    AcceptedAnalysisBundle,
    CurrentObservationFact,
    collision_safe_record_id,
    deterministic_record_id,
    IntegrationRecord,
    IntegrationSession,
    IntegrationValidation,
    make_record_id,
    validate_record_id,
)
from .integration_review import (
    FidelityFinding,
    FidelityPacket,
    FidelityRepairAuthorization,
    FidelityRepairProgress,
    FidelityResult,
    FidelityReviewResult,
    IntegrationFidelityPacket,
    write_packet,
    write_result,
)
from .reporting import (
    RunReportFinalizer,
    RunReportProjector,
    finalize_run_report,
    project_run_report,
)
from .lifecycle import (
    ACTIVE_GENERATION_POINTER_FILENAME,
    AgentInvocationReceipt,
    GENERATION_DIRECTORY,
    GENERATION_MANIFEST_FILENAME,
    GENERATION_PLAN_FILENAME,
    GENERATION_STATE_FILENAME,
    InvocationReceiptLedger,
    RunLifecycle,
    RunGenerationSnapshot,
    RunLifecycleSnapshot,
    classify_invocation_terminal_reason,
    classify_terminal_reason,
    recovery_classification,
)
from .run_extension import (
    DataRefreshNotSafeError,
    DataRefreshSupersededError,
    GenerationManifest,
    RequirementRunExtension,
    RequirementRunGeneration,
    RunExtension,
)
from .data_revisions import (
    CURRENT_POINTER_PATH,
    DATA_REVISION_POINTER_SCHEMA_VERSION,
    DATA_REVISION_SCHEMA_VERSION,
    DATA_ROOM_ROOT,
    PENDING_DATA_REFRESH_ARCHIVE_ROOT,
    PENDING_DATA_REFRESH_PATH,
    PENDING_DATA_REFRESH_SCHEMA_VERSION,
    REVISION_TRANSACTION_PATH,
    REVISION_TRANSACTION_SCHEMA_VERSION,
    REVISION_ARCHIVE_FILENAME,
    REVISION_CATALOG_FILENAME,
    REVISION_MANIFEST_FILENAME,
    REVISION_ROOT,
    DataRevision,
    DataRevisionError,
    DataRevisionTransaction,
    DataRevisionStore,
    PendingDataRefresh,
    PendingDataRefreshConflict,
    RevisionCASMismatch,
    RevisionConflictError,
)
from .product_contracts import (
    FREEZE_MARKER_FIELDS,
    FreezeMarkers,
    ProductContractError,
    decode_freeze_markers,
    validate_freeze_markers,
)
from .durable import (
    AcceptedSnapshot,
    ArtifactProgress,
    ExecutionAttempt,
    ITEM_STATE_FIELDS,
    ITEM_STATE_SCHEMA,
    ItemWorkspace,
    ProgressDecision,
)
from .references import (
    DATA_ASSET_REFERENCE,
    OPERATION_RESULT_REFERENCE,
    REFERENCE_DISCRIMINATOR,
    decode_explicit_reference,
    decode_reference_value,
    encode_explicit_reference,
    encode_reference_value,
    is_explicit_reference_mapping,
)

__version__ = DEFAULT_CORE_VERSION

__all__ = [
    "CONTROL_PLANE_DIRNAME", "COORDINATOR_EVENTS_FILENAME", "COORDINATOR_LOCK_FILENAME", "COORDINATOR_SPEC_FILENAME", "COORDINATOR_STATE_FILENAME",
    "CommandRoleAdapter", "CodexExecConfig", "CodexRoleAdapter", "CoordinatorConflictError",
    "CoordinatorError", "CoordinatorIntegrityError", "CoordinatorProductionBindingMismatch", "CoordinatorPublicationError", "CoordinatorRunSpec",
    "CoordinatorStatus", "MappingRoleAdapter", "PlannerActionProvider", "RequirementPlannerProvider", "RoleAdapter", "RoleExecution", "RoleRunner", "RunCoordinator",
    "ROLE_MODEL_CONTRACT", "ROLE_ACTION_CONTRACT", "ACTION_ROLE_CONTRACT", "PRODUCTION_ROLE_MODEL_CONTRACT", "PRODUCTION_ROLE_ACTION_CONTRACT",
    "build_role_prompt", "logical_action_fingerprint", "production_role_routing", "role_model_route", "role_route_for_action", "start_coordinator", "validate_role_action_contract",
    "SUPERVISOR_ROLE", "SUPERVISOR_ATTENTION_STATUSES", "SUPERVISOR_CLEAN_STATUSES", "CodexSupervisorAdapter", "FoundrySupervisor", "SupervisorAgent", "SupervisorObservation", "SupervisorRepairResult", "SupervisorResult", "build_supervisor_prompt",
    "AggregationSpec", "AllowedRootError", "CanonicalMapping", "DEFAULT_CORE_VERSION", "DEFAULT_SKILL_VERSION",
    "ActionDispatcher", "AutopilotTick", "LocalRunAutopilot",
    "CapabilityDescriptor", "CatalogCounts", "CoreExecutionResult", "CoreRuntime", "DataAssetRef", "DataRoom",
    "DataRoomCatalogEntry", "DataRoomMember", "DataRoomWorkbench", "DocumentRef", "FieldRef",
    "PreparedAsset", "PreparedAssetRegistry", "AcceptedSnapshot", "ArtifactProgress", "ExecutionAttempt", "ITEM_STATE_FIELDS",
    "ITEM_STATE_SCHEMA", "ItemWorkspace", "ProgressDecision",
    "IdentityCandidate", "IdentityDecision",
    "IdentityMappingView", "MappingCompletenessAdvisory",
    "SemanticPromotionSuggestion", "suggest_semantic_promotions",
    "IdentityEvidence", "IncidentRecord", "ImplementationTransition", "KnowledgeDelta", "LEMRef", "LivingEnterpriseModel",
    "LEMCommittedBinding", "LEMProjection", "LivingEnterpriseModelProjector",
    "EntityResolutionResult", "IdentityDomainScope", "IdentityDomainRequest", "EntityResolutionWorkspace", "IdentityDomainReservation",
    "ResolutionCapacity", "ResolutionCommit", "StaleIdentityScopeError", "WorkerLease", "replay_ready_commits",
    "OntologyItem", "OperationReceipt", "OperationResultRef", "OperationSpec",
    "PhaseTimingRecord",
    "PopulationLedger", "PreparedAssetDescriptor", "PreparedAssetRef",
    "RequirementAnalysisPlan", "RequirementAnalysisTask", "RequirementRecord", "RunCache",
    "PLANNER_INCIDENT_FILENAME", "SUPERVISOR_PLAN_FILENAME", "PlannerAction",
    "RequirementExecutionGroup", "RequirementExecutionPlan", "RequirementRunSnapshot",
    "RequirementSupervisorWorkspace", "compact_catalog_payload",
    "RunTelemetrySummary", "TableRef", "TelemetryEvent", "TelemetryRecorder",
    "RunContext", "aggregate_rows", "apply_decision", "capability_catalog",
    "compare_results", "discover", "generate_candidates", "get_capability",
    "mapping_coverage", "measure_relationship", "normalize_rows",
    "normalize_value", "observation_as_of", "parse_date", "parse_number", "preview", "profile_rows",
    "profile_source", "read_rows", "register_source", "reproduce",
    "CURRENT_POINTER_PATH", "DATA_REVISION_POINTER_SCHEMA_VERSION", "DATA_REVISION_SCHEMA_VERSION",
    "DATA_ROOM_ROOT", "REVISION_ARCHIVE_FILENAME", "REVISION_CATALOG_FILENAME",
    "REVISION_MANIFEST_FILENAME", "REVISION_ROOT", "DataRevision", "DataRevisionError",
    "DataRevisionStore", "DataRevisionTransaction", "PendingDataRefresh", "PendingDataRefreshConflict",
    "PENDING_DATA_REFRESH_ARCHIVE_ROOT", "PENDING_DATA_REFRESH_PATH", "PENDING_DATA_REFRESH_SCHEMA_VERSION",
    "REVISION_TRANSACTION_PATH", "REVISION_TRANSACTION_SCHEMA_VERSION",
    "RevisionCASMismatch", "RevisionConflictError",
    "write_artifact", "write_manifest", "require_allowed_roots",
    "DATA_ASSET_REFERENCE", "OPERATION_RESULT_REFERENCE", "REFERENCE_DISCRIMINATOR",
    "decode_explicit_reference", "decode_reference_value", "encode_explicit_reference",
    "encode_reference_value", "is_explicit_reference_mapping",
    "ANALYSIS_SOURCE_MAP_ENV", "BoundAnalysisContext", "CatalogSnapshot", "ContextPayloadRef", "ControlledScriptRunner",
    "canonical_context_payload",
    "ScriptExecutionReceipt", "ScriptRunReport", "ScriptValidationResult", "load_bound_analysis_context", "load_selected_source_ids",
    "SemanticSelectionRef", "SemanticSnapshotRef", "SemanticSnapshotStore",
    "ANALYTICAL_ARTIFACT_SCHEMA_VERSION", "ANALYTICAL_ARTIFACT_TYPES", "AnalyticalArtifact", "AnalyticalArtifactError",
    "AnalyticalArtifactValidationError", "DataProfileArtifact", "KpiTableArtifact",
    "SegmentProfilesArtifact", "SegmentationModelArtifact", "artifact_from_dict",
    "canonical_content_hash", "canonical_json", "AnalyticsDependencyError", "AnalyticsInputError", "MetricDefinition",
    "TabularInput", "compute_kpi_table", "ingest_tabular", "fingerprint_source", "load_tabular", "profile_data", "score_segments", "segment_customers",
    "AnalystAnswer", "AnalystBrief", "AnalystSource", "AnalystWorkspace",
    "BusinessReviewAdapter", "DataInsufficiencyConclusion", "EvidenceNote", "IdentityDomainProposal", "AnalyticalRelationshipEvidence", "ReviewFinding", "SpecialistMemo", "SpecialistTask",
    "AcceptedAnalysisBundle", "CurrentObservationFact", "IntegrationRecord", "IntegrationSession", "IntegrationValidation",
    "IntegrationFidelityPacket", "FidelityPacket", "FidelityFinding", "FidelityResult", "FidelityReviewResult", "FidelityRepairAuthorization", "FidelityRepairProgress", "deterministic_record_id",
    "collision_safe_record_id", "make_record_id", "validate_record_id", "write_packet", "write_result",
    "RunReportFinalizer", "RunReportProjector", "finalize_run_report", "project_run_report",
    "ACTIVE_GENERATION_POINTER_FILENAME", "GENERATION_DIRECTORY", "GENERATION_MANIFEST_FILENAME",
    "GENERATION_PLAN_FILENAME", "GENERATION_STATE_FILENAME", "AgentInvocationReceipt", "InvocationReceiptLedger",
    "RunGenerationSnapshot", "RunLifecycle", "RunLifecycleSnapshot", "GenerationManifest", "RequirementRunGeneration",
    "DataRefreshNotSafeError", "DataRefreshSupersededError", "RequirementRunExtension", "RunExtension",
    "classify_invocation_terminal_reason", "classify_terminal_reason", "recovery_classification",
    "FREEZE_MARKER_FIELDS", "FreezeMarkers", "ProductContractError", "decode_freeze_markers",
    "validate_freeze_markers",
]
